site_name: Componentizing Autonomous Underwater Vehicles by Physical-runnning Algorithms

nav:
    - Home: index.md
    - Hardware:
      - Controller: controlador.md
      - Sensors: sensores.md
      - Actuators: actuadores.md
    - Genetic Algorithms: 
      - Arduino Documentation: documentacion.md
      #- Matlab: matlab.md
      - R-Studio: r.md
    - Laboratory: lab.md
    - Results: resultados.md


theme:
  name: material
  palette:
    primary: blue grey
  icon:
    logo: material/desktop-classic

markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences